Add model parameter to generate_samples() calls
- Adds piper_model_path config parameter support
- Fixes TypeError: generate_samples() missing 1 required positional argument: 'model'
- Uses default path ./piper-sample-generator/models/en_US-libritts_r-medium.pt if not specified in config